import { Metadata } from "next"
import Link from "next/link"
import { ArrowLeft, Shield } from "lucide-react"

export const metadata: Metadata = {
  title: "Terms of Service | Clarus",
  description: "Terms of Service for Clarus",
}

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-black flex flex-col">
      {/* Simple Header */}
      <header className="border-b border-white/[0.08] bg-black/60 backdrop-blur-xl">
        <div className="max-w-4xl mx-auto px-4 py-4">
          <Link href="/" className="inline-flex items-center gap-2 text-white/60 hover:text-white transition-colors">
            <ArrowLeft className="w-4 h-4" />
            <span className="text-sm">Back to Home</span>
          </Link>
        </div>
      </header>

      {/* Content */}
      <main className="flex-1 max-w-4xl mx-auto px-4 py-12">
        {/* Title */}
        <div className="flex items-center gap-4 mb-8">
          <div className="w-12 h-12 bg-gradient-to-br from-[#1d9bf0] to-[#1a8cd8] rounded-xl flex items-center justify-center shadow-lg">
            <Shield className="w-6 h-6 text-white" />
          </div>
          <div>
            <h1 className="text-3xl font-bold text-white">Terms of Service</h1>
            <p className="text-white/50 text-sm">Last updated: January 29, 2026</p>
          </div>
        </div>

        {/* Terms Content */}
        <div className="prose prose-invert max-w-none">
          <div className="space-y-8 text-white/70">
            <section>
              <h2 className="text-xl font-semibold text-white mb-4">1. Acceptance of Terms</h2>
              <p className="leading-relaxed">
                By accessing or using Clarus (&quot;the Service&quot;), operated by InfoSecOps LLC (&quot;we,&quot; &quot;us,&quot; or &quot;our&quot;), you agree to be bound by these Terms of Service (&quot;Terms&quot;). If you do not agree to these Terms, do not use the Service. We may update these Terms at any time by posting the revised version on this page. Your continued use of the Service after any changes constitutes acceptance of the updated Terms.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-white mb-4">2. Description of Service</h2>
              <p className="leading-relaxed">
                Clarus is an AI-powered content analysis tool that helps users understand and evaluate online content, including articles, videos, social media posts, and PDF documents. The Service provides automated analysis including summaries, quality assessments, fact-checking indicators, and actionable insights. All analysis is generated by artificial intelligence and is provided for informational purposes only.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-white mb-4">3. User Accounts</h2>
              <p className="leading-relaxed mb-3">
                To use certain features of the Service, you must create an account. You agree to:
              </p>
              <ul className="list-disc pl-6 space-y-2">
                <li>Provide accurate and complete registration information</li>
                <li>Maintain the security and confidentiality of your account credentials</li>
                <li>Promptly notify us of any unauthorized use of your account</li>
                <li>Accept full responsibility for all activities that occur under your account</li>
              </ul>
              <p className="leading-relaxed mt-4">
                You must be at least 16 years of age to create an account. By creating an account, you represent and warrant that you meet this age requirement.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-white mb-4">4. User Responsibility for Content</h2>
              <p className="leading-relaxed mb-3">
                You are solely responsible for all URLs, videos, articles, documents, and other content you submit to the Service for analysis. By submitting content for analysis, you represent and warrant that:
              </p>
              <ul className="list-disc pl-6 space-y-2">
                <li>You have the legal right to access the submitted content</li>
                <li>The content does not violate any applicable law or regulation</li>
                <li>You will not use the Service to analyze content for any unlawful purpose</li>
                <li>You understand that Clarus does not endorse, verify, or assume liability for any content you submit</li>
              </ul>
              <p className="leading-relaxed mt-4">
                Clarus is a tool that analyzes publicly available content at your direction. We are not responsible for the nature, accuracy, or legality of the content you choose to analyze. Each user bears full responsibility for the material they access and submit to the Service.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-white mb-4">5. Prohibited Uses</h2>
              <p className="leading-relaxed mb-3">
                You agree not to use the Service to:
              </p>
              <ul className="list-disc pl-6 space-y-2">
                <li>Analyze, access, or distribute content that contains child sexual abuse material (CSAM) or exploits minors in any way</li>
                <li>Analyze content that promotes terrorism, violence, or incitement to harm</li>
                <li>Violate any applicable federal, state, local, or international law or regulation</li>
                <li>Infringe upon the intellectual property rights of others</li>
                <li>Engage in harassment, stalking, or doxxing of any individual</li>
                <li>Attempt to reverse-engineer, decompile, or disassemble the Service</li>
                <li>Use automated bots, scrapers, or other automated means to access the Service without our written permission</li>
                <li>Interfere with or disrupt the Service or its infrastructure</li>
                <li>Circumvent any usage limits, rate limiting, or access controls</li>
                <li>Use the Service for competitive intelligence gathering against Clarus</li>
              </ul>
              <p className="leading-relaxed mt-4">
                We reserve the right to investigate and take appropriate action against anyone who, in our sole discretion, violates this provision, including removing content, suspending or terminating accounts, and reporting to law enforcement authorities.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-white mb-4">6. AI-Generated Content Disclaimer</h2>
              <p className="leading-relaxed mb-3">
                All analysis, summaries, fact-checks, quality assessments, and recommendations provided by Clarus are generated by artificial intelligence models. You acknowledge and agree that:
              </p>
              <ul className="list-disc pl-6 space-y-2">
                <li>AI-generated analysis may contain errors, inaccuracies, or incomplete information</li>
                <li>The Service does not provide legal, financial, medical, or professional advice of any kind</li>
                <li>You should not rely solely on Clarus analysis for any important decision</li>
                <li>Fact-check indicators are AI assessments, not definitive determinations of truth</li>
                <li>You should independently verify any information that is important to you through authoritative sources</li>
              </ul>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-white mb-4">7. Subscription Plans and Payment</h2>
              <p className="leading-relaxed mb-3">
                Clarus offers free and paid subscription plans. By subscribing to a paid plan, you agree to the following:
              </p>
              <ul className="list-disc pl-6 space-y-2">
                <li><strong className="text-white">Billing:</strong> Subscriptions are billed in advance on a monthly or annual basis depending on the plan you select</li>
                <li><strong className="text-white">Auto-Renewal:</strong> Subscriptions automatically renew at the end of each billing period unless you cancel before the renewal date</li>
                <li><strong className="text-white">No Refunds:</strong> All payments are non-refundable. We do not provide refunds or credits for partial billing periods, unused features, or dissatisfaction with the Service</li>
                <li><strong className="text-white">Cancellation:</strong> You may cancel your subscription at any time through your account settings or by contacting us. Upon cancellation, your paid features will remain active until the end of your current billing period, after which your account will revert to the free plan</li>
                <li><strong className="text-white">Price Changes:</strong> We reserve the right to change subscription prices. We will provide at least 30 days notice before any price increase takes effect for existing subscribers</li>
              </ul>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-white mb-4">8. Shareable Links</h2>
              <p className="leading-relaxed">
                The Service allows you to generate shareable links to your analyses. By sharing a link, you understand that anyone with the link can view the analysis in read-only mode without authentication. You are responsible for managing who you share links with. Clarus is not liable for any consequences arising from your decision to share an analysis.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-white mb-4">9. Intellectual Property</h2>
              <p className="leading-relaxed mb-3">
                The Service, including its design, code, features, branding, and AI models, is owned by InfoSecOps LLC and is protected by copyright, trademark, and other intellectual property laws. You retain ownership of the content you submit for analysis. By using the Service, you grant us a limited, non-exclusive license to process your submitted content solely for the purpose of providing the Service to you.
              </p>
              <p className="leading-relaxed">
                You may not copy, modify, distribute, or create derivative works from any part of the Service without our prior written consent.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-white mb-4">10. DMCA and Copyright Complaints</h2>
              <p className="leading-relaxed mb-3">
                We respect intellectual property rights. If you believe that content accessible through the Service infringes your copyright, please send a written notice to our designated agent with the following information:
              </p>
              <ul className="list-disc pl-6 space-y-2">
                <li>A description of the copyrighted work you claim has been infringed</li>
                <li>The URL or location of the allegedly infringing material on our Service</li>
                <li>Your contact information (name, address, email, phone number)</li>
                <li>A statement that you have a good faith belief that the use is not authorized by the copyright owner</li>
                <li>A statement, made under penalty of perjury, that the information in your notice is accurate and that you are the copyright owner or authorized to act on behalf of the owner</li>
                <li>Your physical or electronic signature</li>
              </ul>
              <p className="leading-relaxed mt-4">
                Send DMCA notices to:{" "}
                <a href="mailto:legal@infosecops.io" className="text-[#1d9bf0] hover:underline">
                  legal@infosecops.io
                </a>
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-white mb-4">11. Disclaimer of Warranties</h2>
              <p className="leading-relaxed uppercase text-xs tracking-wide">
                THE SERVICE IS PROVIDED &quot;AS IS&quot; AND &quot;AS AVAILABLE&quot; WITHOUT WARRANTIES OF ANY KIND, WHETHER EXPRESS, IMPLIED, OR STATUTORY. WE EXPRESSLY DISCLAIM ALL WARRANTIES, INCLUDING BUT NOT LIMITED TO IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, AND ACCURACY. WE DO NOT WARRANT THAT THE SERVICE WILL BE UNINTERRUPTED, ERROR-FREE, SECURE, OR FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS. WE MAKE NO WARRANTY REGARDING THE ACCURACY, RELIABILITY, OR COMPLETENESS OF ANY AI-GENERATED ANALYSIS OR CONTENT.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-white mb-4">12. Limitation of Liability</h2>
              <p className="leading-relaxed uppercase text-xs tracking-wide">
                TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL INFOSECOPS LLC, ITS OFFICERS, DIRECTORS, EMPLOYEES, OR AGENTS BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING BUT NOT LIMITED TO LOSS OF PROFITS, DATA, USE, GOODWILL, OR OTHER INTANGIBLE LOSSES, ARISING OUT OF OR RELATED TO YOUR USE OF OR INABILITY TO USE THE SERVICE, ANY CONDUCT OR CONTENT OF ANY THIRD PARTY ON THE SERVICE, ANY CONTENT OBTAINED FROM THE SERVICE, OR UNAUTHORIZED ACCESS TO OR ALTERATION OF YOUR DATA, WHETHER BASED ON WARRANTY, CONTRACT, TORT (INCLUDING NEGLIGENCE), OR ANY OTHER LEGAL THEORY, WHETHER OR NOT WE HAVE BEEN INFORMED OF THE POSSIBILITY OF SUCH DAMAGE. OUR TOTAL AGGREGATE LIABILITY FOR ALL CLAIMS RELATED TO THE SERVICE SHALL NOT EXCEED THE AMOUNT YOU PAID US IN THE TWELVE (12) MONTHS PRECEDING THE CLAIM.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-white mb-4">13. Indemnification</h2>
              <p className="leading-relaxed">
                You agree to indemnify, defend, and hold harmless InfoSecOps LLC and its officers, directors, employees, contractors, and agents from and against any and all claims, damages, obligations, losses, liabilities, costs, and expenses (including reasonable attorney&apos;s fees) arising from: (a) your use of the Service; (b) your violation of these Terms; (c) your violation of any rights of a third party, including intellectual property rights; or (d) the content you submit to the Service for analysis.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-white mb-4">14. Termination</h2>
              <p className="leading-relaxed">
                We may terminate or suspend your account and access to the Service immediately, without prior notice or liability, for any reason, including but not limited to a breach of these Terms. Upon termination: (a) your right to use the Service will cease immediately; (b) if you have an active paid subscription, no refund will be issued for the remaining billing period; (c) we may delete your account data in accordance with our Privacy Policy. You may terminate your account at any time by contacting us or through your account settings.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-white mb-4">15. Governing Law and Dispute Resolution</h2>
              <p className="leading-relaxed">
                These Terms shall be governed by and construed in accordance with the laws of the United States and the State of the operator&apos;s principal place of business, without regard to conflict of law principles. Any dispute arising from these Terms or the Service shall first be attempted to be resolved through good-faith negotiation. If negotiation fails, disputes shall be resolved through binding arbitration in accordance with the rules of the American Arbitration Association, except that either party may seek injunctive relief in a court of competent jurisdiction. You agree to waive any right to a jury trial or to participate in a class action.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-white mb-4">16. Severability</h2>
              <p className="leading-relaxed">
                If any provision of these Terms is held to be invalid, illegal, or unenforceable by a court of competent jurisdiction, the remaining provisions shall continue in full force and effect. The invalid provision shall be modified to the minimum extent necessary to make it valid and enforceable while preserving the original intent.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-white mb-4">17. Entire Agreement</h2>
              <p className="leading-relaxed">
                These Terms, together with our Privacy Policy, constitute the entire agreement between you and InfoSecOps LLC regarding the Service and supersede all prior or contemporaneous agreements, communications, and proposals, whether oral or written.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-white mb-4">18. Contact Information</h2>
              <p className="leading-relaxed mb-3">
                If you have any questions about these Terms of Service, please contact us:
              </p>
              <div className="p-4 bg-white/[0.04] border border-white/[0.08] rounded-xl mt-4">
                <p className="text-white/70 mb-1">
                  <strong className="text-white">InfoSecOps LLC</strong>
                </p>
                <p className="text-white/70">
                  Email:{" "}
                  <a href="mailto:legal@infosecops.io" className="text-[#1d9bf0] hover:underline">
                    legal@infosecops.io
                  </a>
                </p>
                <p className="text-white/70 mt-1">
                  General inquiries:{" "}
                  <a href="mailto:support@infosecops.io" className="text-[#1d9bf0] hover:underline">
                    support@infosecops.io
                  </a>
                </p>
              </div>
            </section>
          </div>
        </div>
      </main>
    </div>
  )
}
